nama=input("Nama                 : ")
nim=input("NIM                  : ")
kelas=input("Kelas Pararel        : ")
ttl=input("Tempat/Tanggal Lahir : ")
alamat=input("Alamat               : ")
hobby=input("Hobby                : ")
no=input("No. Hp               : ")
print("\n")
print("Nama                 : ",nama)
print("NIM                  : ",nim)
print("Kelas Pararel        : ",kelas)
print("Tempat/Tanggal Lahir : ",ttl)
print("Alamat               : ",alamat)
print("Hobby                : ",hobby)
print("No. Hp               : ",no)
