print("#################################\n")
print("#\t\t\t\t#\n")
print("#\tAditya Oktaviari\t#\n")
print("#\t 2210817110008\t\t#\n")
print("#\t\t\t\t#\n")
print("#################################")